Vagrant.configure("2") do |config|
  
  config.vm.disk :disk, size: "20GB", primary: true, name: "Paolo", disk_ext: "vdi"
  config.vm.box = "ubuntu/xenial64"
  
  # bug fix https://github.com/hashicorp/vagrant/issues/11890#issuecomment-698584763
  config.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--uart1", "0x3F8", "4"]
    v.customize ["modifyvm", :id, "--uartmode1", "file", File::NULL]
  end

  config.vm.network "forwarded_port", guest: 31130, host: 8082
  config.vm.network "private_network", ip: "192.168.68.8"
  config.vm.synced_folder "shared-folder", "/vagrant_data"
  
  config.vm.provider "virtualbox" do |vb|
     vb.memory = "2048"
     vb.cpus = 1
	 #  The vm name must not contain underscore or capital char!
     vb.name = "k8snode1"
  end

  config.vm.provision "shell", inline: <<-SHELL
  
    # Nodes network setting
	hostnamectl --static set-hostname k8snode1
	echo "192.168.68.7 k8smaster" >> /etc/hosts
	echo "192.168.68.8 k8snode1" >> /etc/hosts
	echo "192.168.68.9 k8snode2" >> /etc/hosts
	
	# Set proxy settings
	echo "export HTTP_PROXY='http://proxy.url:8080'" >> /etc/profile.d/proxy-list.sh
	echo "export HTTPS_PROXY='http://proxy.url:8080'" >> /etc/profile.d/proxy-list.sh
	echo "export NO_PROXY='127.0.0.1,0.0.0.0,localhost,10.152.183.1:443,192.168.68.7,192.168.68.8,192.168.68.9,k8snode2,k8smaster,k8snode1'" >> /etc/profile.d/proxy-list.sh
	echo "export http_proxy='http://proxy.url:8080'" >> /etc/profile.d/proxy-list.sh
	echo "export https_proxy='http://proxy.url:8080'" >> /etc/profile.d/proxy-list.sh
	echo "export no_proxy='127.0.0.1,0.0.0.0,localhost,10.152.183.1:443,192.168.68.7,192.168.68.8,192.168.68.9,k8snode2,k8smaster,k8snode1'" >> /etc/profile.d/proxy-list.sh
	
	# Set apt proxy settings
	echo 'Acquire::http::Proxy "http://proxy.url:8080";' >> /etc/apt/apt.conf.d/proxy.conf
	echo 'Acquire::https::Proxy "http://proxy.url:8080";' >> /etc/apt/apt.conf.d/proxy.conf
  
  	# Set snap proxy settings
	sudo snap set system proxy.https="http://proxy.url:8080"
	sudo snap set system proxy.http="http://proxy.url:8080"
	
	# Install microk8s
	sudo snap install microk8s --classic --channel=1.21
	
	echo "HTTPS_PROXY=http://proxy.url:8080" >> /var/snap/microk8s/current/args/containerd-env
	echo "NO_PROXY=127.0.0.1,10.152.183.1:443,0.0.0.0,192.168.68.7,192.168.68.8,192.168.68.9,k8snode2,k8smaster,k8snode1" >> /var/snap/microk8s/current/args/containerd-env
	
	echo "HTTP_PROXY=proxy.url:8080" >> /etc/environment
	echo "HTTPS_PROXY=proxy.url:8080" >> /etc/environment
	echo "NO_PROXY=127.0.0.1,10.152.183.1:443,0.0.0.0,192.168.68.7,192.168.68.8,192.168.68.9,k8snode2,k8smaster,k8snode1" >> /etc/environment
	
	echo '      [plugins."io.containerd.grpc.v1.cri".registry.mirrors."artifactory.url"]
        endpoint = ["artifactory.url"]' >> /var/snap/microk8s/current/args/containerd-template.toml

	sudo microk8s stop
	sudo microk8s start
	
	# Default user is 'vagrant', password 'vagrant'
	sudo usermod -a -G microk8s vagrant
	sudo chown -f -R vagrant ~/.kube
	newgrp microk8s
	
	sudo microk8s enable dns
	sudo microk8s enable storage
	
	echo "alias k='microk8s kubectl'" >> /home/vagrant/.bash_aliases
	echo "alias mk='microk8s'" >> /home/vagrant/.bash_aliases
  
  SHELL

end









